envVars:
 dev:
  ## Variables de Arquitectura
  PROJECT_NAME: "qgdiag-microservicio-python-test"
  ENVIRONMENT: "development"

  ORCHESTRATOR_URL: "https://qgdiag.backend-desa.unicajasc.corp/qgdiag-ms-orquestador-iag"
  ORCHESTRATOR_PORT: "443"
  URL_CERT: "https://aebd.backend-desa.unicajasc.corp:443/qgd-arq-ms-pkm/jwks"

 pre:
  ## Variables de Arquitectura
  PROJECT_NAME: "qgdiag-microservicio-python-test"
  ENVIRONMENT: "preproduccion"

 pro:
 ## Variables de Arquitectura
  PROJECT_NAME: "qgdiag-microservicio-python-test"
  ENVIRONMENT: "produccion"

  ## Variables del microservicio
